MODEL:
  META_ARCHITECTURE: "VideoPanopticFCN"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/data/detectron2_modelzoo/basemodel/R-50-MSRA.pkl"
  MASK_ON: True
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [1.0, 1.0, 1.0]
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  POSITION_HEAD:
    THING:
      NUM_CLASSES: 58
    STUFF:
      NUM_CLASSES: 67
  SEM_SEG_HEAD:
    NUM_CLASSES: 67
  USE_CLIPFUSE: False
  TEMPORAL_KERNAL: False

DATASETS:
#  TRAIN: ("coco_2017_train_panoptic_separated",)
#  TEST: ("coco_2017_val_panoptic_separated",)
  TRAIN: ("panoVSPW_vps_video_train",)
  TEST: ("panoVSPW_vps_video_val",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
SOLVER:
  BASE_LR: 0.0005
  WEIGHT_DECAY: 1e-4
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POLY_LR_POWER: 0.9
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  WARMUP_METHOD: "linear"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 35.0
  IMS_PER_BATCH: 16
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (608, 748, 806, 864, 922, 980, 1036, 1094, 1152, 1206, 1267, 1324, 1382, 1440)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 720
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  FORMAT: "RGB"
  TRAIN_SHUFFLE_TIMES: 1
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (608, 608)
#  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
#  MIN_SIZE_TRAIN_SAMPLING: "choice"
#  MIN_SIZE_TEST: 800
#  MAX_SIZE_TRAIN: 1333
#  MAX_SIZE_TEST: 1333
#  MASK_FORMAT: "bitmask"
  DATASET_MAPPER_NAME: "video_mapper"
TRAIN:
  USE_CON_LOSS: False
VERSION: 2

